package application

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
)

type MockResumeGenerator struct{}

func NewMockResumeGenerator() *MockResumeGenerator {
	return &MockResumeGenerator{}
}

func (g *MockResumeGenerator) GenerateTailoredResume(
	ctx context.Context,
	jobID int64,
	outputPath string,
) error {
	if jobID <= 0 {
		return fmt.Errorf("job ID must be positive")
	}

	if outputPath == "" {
		return fmt.Errorf("output path is required")
	}

	if err := ctx.Err(); err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("create resume directory: %w", err)
	}

	content := fmt.Sprintf(
		"JobClaw Tailored Resume\n\nJob ID: %d\n\nGenerated by JobClaw.",
		jobID,
	)

	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write tailored resume: %w", err)
	}

	return nil
}
